from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eduverse_server.models.base_model import Model
from eduverse_server import util


class AttendanceRecord(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _date=None, present=None):  # noqa: E501
        """AttendanceRecord - a model defined in OpenAPI

        :param _date: The _date of this AttendanceRecord.  # noqa: E501
        :type _date: str
        :param present: The present of this AttendanceRecord.  # noqa: E501
        :type present: bool
        """
        self.openapi_types = {
            '_date': str,
            'present': bool
        }

        self.attribute_map = {
            '_date': 'date',
            'present': 'present'
        }

        self.__date = _date
        self._present = present

    @classmethod
    def from_dict(cls, dikt) -> 'AttendanceRecord':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AttendanceRecord of this AttendanceRecord.  # noqa: E501
        :rtype: AttendanceRecord
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this AttendanceRecord.


        :return: The _date of this AttendanceRecord.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this AttendanceRecord.


        :param _date: The _date of this AttendanceRecord.
        :type _date: str
        """

        self.__date = _date

    @property
    def present(self) -> bool:
        """Gets the present of this AttendanceRecord.


        :return: The present of this AttendanceRecord.
        :rtype: bool
        """
        return self._present

    @present.setter
    def present(self, present: bool):
        """Sets the present of this AttendanceRecord.


        :param present: The present of this AttendanceRecord.
        :type present: bool
        """

        self._present = present
