from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eduverse_server.models.base_model import Model
from eduverse_server import util


class AttendanceBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, student_id=None, _date=None, present=None):  # noqa: E501
        """AttendanceBody - a model defined in OpenAPI

        :param student_id: The student_id of this AttendanceBody.  # noqa: E501
        :type student_id: str
        :param _date: The _date of this AttendanceBody.  # noqa: E501
        :type _date: date
        :param present: The present of this AttendanceBody.  # noqa: E501
        :type present: bool
        """
        self.openapi_types = {
            'student_id': str,
            '_date': date,
            'present': bool
        }

        self.attribute_map = {
            'student_id': 'student_id',
            '_date': 'date',
            'present': 'present'
        }

        self._student_id = student_id
        self.__date = _date
        self._present = present

    @classmethod
    def from_dict(cls, dikt) -> 'AttendanceBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The attendance_body of this AttendanceBody.  # noqa: E501
        :rtype: AttendanceBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def student_id(self) -> str:
        """Gets the student_id of this AttendanceBody.


        :return: The student_id of this AttendanceBody.
        :rtype: str
        """
        return self._student_id

    @student_id.setter
    def student_id(self, student_id: str):
        """Sets the student_id of this AttendanceBody.


        :param student_id: The student_id of this AttendanceBody.
        :type student_id: str
        """
        if student_id is None:
            raise ValueError("Invalid value for `student_id`, must not be `None`")  # noqa: E501

        self._student_id = student_id

    @property
    def _date(self) -> date:
        """Gets the _date of this AttendanceBody.


        :return: The _date of this AttendanceBody.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this AttendanceBody.


        :param _date: The _date of this AttendanceBody.
        :type _date: date
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def present(self) -> bool:
        """Gets the present of this AttendanceBody.


        :return: The present of this AttendanceBody.
        :rtype: bool
        """
        return self._present

    @present.setter
    def present(self, present: bool):
        """Sets the present of this AttendanceBody.


        :param present: The present of this AttendanceBody.
        :type present: bool
        """
        if present is None:
            raise ValueError("Invalid value for `present`, must not be `None`")  # noqa: E501

        self._present = present
