from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eduverse_server.models.base_model import Model
from eduverse_server.models.pagination import Pagination
from eduverse_server.models.user import User
from eduverse_server import util

from eduverse_server.models.pagination import Pagination  # noqa: E501
from eduverse_server.models.user import User  # noqa: E501

class InlineResponse2001(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, pagination=None):  # noqa: E501
        """InlineResponse2001 - a model defined in OpenAPI

        :param data: The data of this InlineResponse2001.  # noqa: E501
        :type data: List[User]
        :param pagination: The pagination of this InlineResponse2001.  # noqa: E501
        :type pagination: Pagination
        """
        self.openapi_types = {
            'data': List[User],
            'pagination': Pagination
        }

        self.attribute_map = {
            'data': 'data',
            'pagination': 'pagination'
        }

        self._data = data
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[User]:
        """Gets the data of this InlineResponse2001.


        :return: The data of this InlineResponse2001.
        :rtype: List[User]
        """
        return self._data

    @data.setter
    def data(self, data: List[User]):
        """Sets the data of this InlineResponse2001.


        :param data: The data of this InlineResponse2001.
        :type data: List[User]
        """

        self._data = data

    @property
    def pagination(self) -> Pagination:
        """Gets the pagination of this InlineResponse2001.


        :return: The pagination of this InlineResponse2001.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: Pagination):
        """Sets the pagination of this InlineResponse2001.


        :param pagination: The pagination of this InlineResponse2001.
        :type pagination: Pagination
        """

        self._pagination = pagination
