from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eduverse_server.models.base_model import Model
from eduverse_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, balance=None, currency=None):  # noqa: E501
        """InlineResponse2003 - a model defined in OpenAPI

        :param balance: The balance of this InlineResponse2003.  # noqa: E501
        :type balance: int
        :param currency: The currency of this InlineResponse2003.  # noqa: E501
        :type currency: str
        """
        self.openapi_types = {
            'balance': int,
            'currency': str
        }

        self.attribute_map = {
            'balance': 'balance',
            'currency': 'currency'
        }

        self._balance = balance
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def balance(self) -> int:
        """Gets the balance of this InlineResponse2003.


        :return: The balance of this InlineResponse2003.
        :rtype: int
        """
        return self._balance

    @balance.setter
    def balance(self, balance: int):
        """Sets the balance of this InlineResponse2003.


        :param balance: The balance of this InlineResponse2003.
        :type balance: int
        """

        self._balance = balance

    @property
    def currency(self) -> str:
        """Gets the currency of this InlineResponse2003.


        :return: The currency of this InlineResponse2003.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this InlineResponse2003.


        :param currency: The currency of this InlineResponse2003.
        :type currency: str
        """

        self._currency = currency
