from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eduverse_server.models.base_model import Model
from eduverse_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, subject=None, teacher=None, time=None, room=None):  # noqa: E501
        """InlineResponse2002 - a model defined in OpenAPI

        :param subject: The subject of this InlineResponse2002.  # noqa: E501
        :type subject: str
        :param teacher: The teacher of this InlineResponse2002.  # noqa: E501
        :type teacher: str
        :param time: The time of this InlineResponse2002.  # noqa: E501
        :type time: str
        :param room: The room of this InlineResponse2002.  # noqa: E501
        :type room: str
        """
        self.openapi_types = {
            'subject': str,
            'teacher': str,
            'time': str,
            'room': str
        }

        self.attribute_map = {
            'subject': 'subject',
            'teacher': 'teacher',
            'time': 'time',
            'room': 'room'
        }

        self._subject = subject
        self._teacher = teacher
        self._time = time
        self._room = room

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subject(self) -> str:
        """Gets the subject of this InlineResponse2002.


        :return: The subject of this InlineResponse2002.
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject: str):
        """Sets the subject of this InlineResponse2002.


        :param subject: The subject of this InlineResponse2002.
        :type subject: str
        """

        self._subject = subject

    @property
    def teacher(self) -> str:
        """Gets the teacher of this InlineResponse2002.


        :return: The teacher of this InlineResponse2002.
        :rtype: str
        """
        return self._teacher

    @teacher.setter
    def teacher(self, teacher: str):
        """Sets the teacher of this InlineResponse2002.


        :param teacher: The teacher of this InlineResponse2002.
        :type teacher: str
        """

        self._teacher = teacher

    @property
    def time(self) -> str:
        """Gets the time of this InlineResponse2002.


        :return: The time of this InlineResponse2002.
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time: str):
        """Sets the time of this InlineResponse2002.


        :param time: The time of this InlineResponse2002.
        :type time: str
        """

        self._time = time

    @property
    def room(self) -> str:
        """Gets the room of this InlineResponse2002.


        :return: The room of this InlineResponse2002.
        :rtype: str
        """
        return self._room

    @room.setter
    def room(self, room: str):
        """Sets the room of this InlineResponse2002.


        :param room: The room of this InlineResponse2002.
        :type room: str
        """

        self._room = room
