from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eduverse_server.models.base_model import Model
from eduverse_server import util


class Product(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, product_id=None, name=None, price=None, currency=None):  # noqa: E501
        """Product - a model defined in OpenAPI

        :param product_id: The product_id of this Product.  # noqa: E501
        :type product_id: str
        :param name: The name of this Product.  # noqa: E501
        :type name: str
        :param price: The price of this Product.  # noqa: E501
        :type price: int
        :param currency: The currency of this Product.  # noqa: E501
        :type currency: str
        """
        self.openapi_types = {
            'product_id': str,
            'name': str,
            'price': int,
            'currency': str
        }

        self.attribute_map = {
            'product_id': 'product_id',
            'name': 'name',
            'price': 'price',
            'currency': 'currency'
        }

        self._product_id = product_id
        self._name = name
        self._price = price
        self._currency = currency

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product_id(self) -> str:
        """Gets the product_id of this Product.


        :return: The product_id of this Product.
        :rtype: str
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: str):
        """Sets the product_id of this Product.


        :param product_id: The product_id of this Product.
        :type product_id: str
        """

        self._product_id = product_id

    @property
    def name(self) -> str:
        """Gets the name of this Product.


        :return: The name of this Product.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Product.


        :param name: The name of this Product.
        :type name: str
        """

        self._name = name

    @property
    def price(self) -> int:
        """Gets the price of this Product.


        :return: The price of this Product.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price: int):
        """Sets the price of this Product.


        :param price: The price of this Product.
        :type price: int
        """

        self._price = price

    @property
    def currency(self) -> str:
        """Gets the currency of this Product.


        :return: The currency of this Product.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency: str):
        """Sets the currency of this Product.


        :param currency: The currency of this Product.
        :type currency: str
        """

        self._currency = currency
