from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from eduverse_server.models.base_model import Model
from eduverse_server import util


class Transaction(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, transaction_id=None, type=None, amount=None, _date=None):  # noqa: E501
        """Transaction - a model defined in OpenAPI

        :param transaction_id: The transaction_id of this Transaction.  # noqa: E501
        :type transaction_id: str
        :param type: The type of this Transaction.  # noqa: E501
        :type type: str
        :param amount: The amount of this Transaction.  # noqa: E501
        :type amount: float
        :param _date: The _date of this Transaction.  # noqa: E501
        :type _date: str
        """
        self.openapi_types = {
            'transaction_id': str,
            'type': str,
            'amount': float,
            '_date': str
        }

        self.attribute_map = {
            'transaction_id': 'transaction_id',
            'type': 'type',
            'amount': 'amount',
            '_date': 'date'
        }

        self._transaction_id = transaction_id
        self._type = type
        self._amount = amount
        self.__date = _date

    @classmethod
    def from_dict(cls, dikt) -> 'Transaction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Transaction of this Transaction.  # noqa: E501
        :rtype: Transaction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transaction_id(self) -> str:
        """Gets the transaction_id of this Transaction.


        :return: The transaction_id of this Transaction.
        :rtype: str
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id: str):
        """Sets the transaction_id of this Transaction.


        :param transaction_id: The transaction_id of this Transaction.
        :type transaction_id: str
        """

        self._transaction_id = transaction_id

    @property
    def type(self) -> str:
        """Gets the type of this Transaction.


        :return: The type of this Transaction.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Transaction.


        :param type: The type of this Transaction.
        :type type: str
        """

        self._type = type

    @property
    def amount(self) -> float:
        """Gets the amount of this Transaction.


        :return: The amount of this Transaction.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this Transaction.


        :param amount: The amount of this Transaction.
        :type amount: float
        """

        self._amount = amount

    @property
    def _date(self) -> str:
        """Gets the _date of this Transaction.


        :return: The _date of this Transaction.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this Transaction.


        :param _date: The _date of this Transaction.
        :type _date: str
        """

        self.__date = _date
